[package]
name = "ts3plugin"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
description = """
An abstraction layer that simplifies creating TeamSpeak3 plugins
and stores received data to provide a more convenient API.
"""
repository = "https://github.com/Flakebi/rust-ts3plugin"
documentation = "https://flakebi.github.io/rust-ts3plugin/doc/ts3plugin/"
readme = "README.md"
keywords = ["plugin", "TeamSpeak3"]
license = "MIT/Apache-2.0"
build = "src/build.rs"

[lib]
name = "ts3plugin"

[features]
default = []

[dependencies]
chrono = "0.2"
ts3plugin-sys = "0.2"
lazy_static = "0.2"

# For tests
[build-dependencies]
skeptic = "0.6"

[dev-dependencies]
lazy_static = "0.2"
skeptic = "0.6"

# Use `cargo build --features "clippy"` to see style lints
[dependencies.clippy]
version = "0"
optional = true
