[package]
name = "ts3plugin"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
description = "TeamSpeak3 Plugin API"
repository = "https://github.com/Flakebi/rust-ts3plugin"
readme = "README.md"
license = "MIT/Apache-2.0"
build = "src/build.rs"

[lib]
name = "ts3plugin"

[features]
default = []

[dependencies]
chrono = "*"
libc = "*"

# For tests
[build-dependencies]
skeptic = "0.5"

[dev-dependencies]
lazy_static = "*"
skeptic = "0.5"

# Use `cargo build --features "clippy"` to see style lints
[dependencies.clippy]
version = "*"
optional = true

[dependencies.ts3plugin_sys]
git = "https://github.com/Flakebi/rust-ts3plugin-sys"
