[package]
name = "ts3plugin"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
build = "src/build.rs"

[lib]
name = "ts3plugin"

[dependencies]
chrono = "*"
clippy = "*"
lazy_static = "*"
libc = "*"

[dependencies.ts3plugin_sys]
#git = "https://github.com/Flakebi/rust-ts3plugin-sys"
path = "../ts3plugin_sys"
